version: '3'
services:
  postgres:
    image: postgres:9.6
    #container_name: sda_app_db
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5433:5432"

  webserver:
    #image: puckel/docker-airflow:1.10.1
    image: sda_airflow:latest
    #container_name: sda_app
    build:
      context: https://github.com/puckel/docker-airflow.git#1.10.1
      dockerfile: Dockerfile
      args:
        AIRFLOW_DEPS: gcp_api,s3
        PYTHON_DEPS: sqlalchemy==1.2.0
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - FERNET_KEY=jsDPRErfv8Z_eVTnGfF8ywd19j4pyqE3NpdUBA_oRTo=
    volumes:
      #- airflow_dags:/usr/local/airflow/dags    
      #- airflow_data:/usr/local/airflow/data
      - ./tasks:/usr/local/airflow/tasks:z
      - ./dags:/usr/local/airflow/dags:z
      #- ./ingest:/usr/local/airflow/ingest:z
      - /home/baxterOutput:/usr/local/airflow/ingest:Z
      #- /home/outdir:/usr/local/airflow/results:Z
      - ./processed_data:/usr/local/airflow/processed_data:z
      - ./results:/usr/local/airflow/results:z
      - ./snippets:/usr/local/airflow/snippets:z
      #- /home/Alex/build/airflow/dags:/usr/local/airflow/dags
      #- ./examples/intro-example/dags:/usr/local/airflow/dags
      # Uncomment to include custom plugins
      # - ./plugins:/usr/local/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  airflow_dags:
#  airflow_data:
  airflow_tasks:
  processed_data:
  results:
