version:                "3"
services:
  datascience-notebook:
      image:            jupyter/notebook:latest
      #build:
      #  context: .
      volumes:
        - jupyter-data:/home/jovyan/work
      ports:
        - 8888:8888
      container_name:   datascience-notebook-container
      environment:
        - JUPYTER_ENABLE_LAB=yes

volumes:
   jupyter-data:
