web:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
#  name: 'gitlab'
  hostname: 'gitlab.example.com'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://localhost:8929'
      gitlab_rails['gitlab_shell_ssh_port'] = 2224
  ports:
    - '8929:8929'
    - '2224:22'
#    - '8180:80'
#    - '9443:443'
#    - '922:22'
  volumes:
    - gitlab-config:/etc/config
    - gitlab-logs:/var/log/gitlab
    - gitlab-data:/var/opt/gitlab
