version: "3.2"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
#:5.6.40
    networks:
      - backend
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: example
    volumes:
      #- ./schema:/docker-entrypopint-initdb.d
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    restart: always
    networks:
      - backend
    depends_on:
      - db
    ports:
      - "8080:8080"
networks:
  backend:

volumes:
   mysql-data:

